services:
  postgres:
    image: postgres:16
    container_name: remmy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: remmy
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: remmy_db
    ports:
      - "8080:5432"
    volumes:
      - remmy_pgdata:/var/lib/postgresql/data

volumes:
  remmy_pgdata: